### ISSUE TITLE
Miss File In Sample Code

### ISSUE THREAD

**Issue by johnwatsondev** [JumeiRdGroup/Router#6]
![router sample error](https://user-images.githubusercontent.com/12760754/30465468-f2986180-999c-11e7-810e-585aa79a8b0d.jpg)

This error was occurred in `App.java`with the code of master branch.

**Comment by yjfnypeu** [comment]
This class is a generated file by annotation processor. you can make it by click Build/make project on menu bar.

**Comment by johnwatsondev** [comment]
Thanks very much. :)
