### ISSUE TITLE
提个建议：用app内部webview打开网页，能选择只让自己app打开

### ISSUE THREAD

**Issue by caprice** [JumeiRdGroup/Router#7]
用app内部webview打开网页，而不是每次弹出选择框去挑选哪个应用打开url.  希望能支持，改下
BrowserRoute的这个方法就行了。
![image](https://user-images.githubusercontent.com/2981114/41073218-d7ece338-6a34-11e8-8a4d-c3ed746c32fb.png)
现在只能自己写个BrowserRoute，并且完全copy Router代码，然后改写：
![image](https://user-images.githubusercontent.com/2981114/41073260-139d3914-6a35-11e8-8475-149470f64205.png)

**Comment by yjfnypeu** [comment]
呃。。。你这弄复杂了。需要用自身app打开。你可以参考对启动uri做个前置封装的操作：

1. 给你们app的内置浏览器页面。添加路由链接，比如：example://page/webview

2. 然后在启动入口处，对启动的链接进行http/https的判断。满足条件后重新组装成启动内置浏览器页面的链接：

```
class RouterEntry {
    public void open(String url) {
        if (isHttp(url)) {
            url = Uri.parse("example://page/webview").buildUpon().appendQueryParameter("url", url).toString()
        }
        ...
    }
    ....
}
```

RouterEntry为二次封装入口。一般来说接入第三方使用都推荐应该自己进行一次简单的二次封装之后再进行使用。会很方便

**Comment by caprice** [comment]
嗯，你这种方法的确在基于这个library改动及扩展上更好。谢谢及时回复。可能我考虑的是如何尽量少的修改原有代码，用你们这个方案来一步一步替换。
